# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoppingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionFaceModel'
  pod 'BHPhotoView', :git => 'https://github.com/benhurott/BHPhotoView'

  # Pods for ShoppingApp

end

