# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoppingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'ObjectMapper', '3.3'
  pod 'AlamofireObjectMapper'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Firestore'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'Firebase/Performance'
  pod 'Firebase/Messaging'


  # Pods for ShoppingApp

end

